### ISSUE TITLE
elan-splitter annotations.json is saved in ASCII encoding 

### ISSUE THREAD

**Issue by mjurkus** [CoEDL/elan-helpers#3]
When processing UTF-8 encoded eaf file splitter produces ASCII encoded `annotations.json`

Extracted txt files are created correctly.

```
$ file input.eaf
input.eaf: XML 1.0 document, UTF-8 Unicode text

$ file annotations.json 
annotations.json: ASCII text
```

**Comment by benfoley** [comment]
Hi, try again. I have added `ensure_ascii=False` to the output command. Also changed in the `elan-to-json` code.

**Comment by mjurkus** [comment]
Perfect!
